package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x86_64/jdk8u301/1513/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, June 9, 2021 2:35:52 PM BST
*/

public interface TAG_CODE_SETS
{

  /**
       * The code set component of the IOR multi-component profile structure
       * contains:
       * <ul>
       *   <li>server's native char code set and conversion code sets, and</li>
       *   <li>server's native wchar code set and conversion code sets.</li>
       * </ul>
       * Both char and wchar conversion code sets are listed in order of 
       * preference.
       */
  public static final int value = (int)(1L);
}
