package org.omg.PortableServer;


/**
* org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x86_64/jdk8u301/1513/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, June 9, 2021 2:35:52 PM BST
*/

public interface SERVANT_RETENTION_POLICY_ID
{

  /**
  	 * The value representing SERVANT_RETENTION_POLICY_ID.
  	 */
  public static final int value = (int)(21L);
}
